apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: neo4j

resources:
  - configmap.yaml
  - secret.yaml
  - mcp-neo4j-cypher.yaml
  - mcp-neo4j-memory.yaml
  - mcp-neo4j-data-modeling.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml

commonLabels:
  project: mcp-neo4j
  environment: production
  managed-by: kustomize

images:
  - name: ghcr.io/memenow/mcp-neo4j-cypher
    newTag: latest
  - name: ghcr.io/memenow/mcp-neo4j-memory
    newTag: latest
  - name: ghcr.io/memenow/mcp-neo4j-data-modeling
    newTag: latest