apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: neo4j

resources:
  - ../../base
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml

patches:
  - path: patches.yaml

labels:
  - pairs:
      app.kubernetes.io/instance: production