apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mcp-cypher-pdb
  namespace: neo4j
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: mcp
      app.kubernetes.io/component: cypher
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mcp-memory-pdb
  namespace: neo4j
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: mcp
      app.kubernetes.io/component: memory
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mcp-modeling-pdb
  namespace: neo4j
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: mcp
      app.kubernetes.io/component: modeling
