apiVersion: v1
kind: Service
metadata:
  name: mcp-cypher
  labels:
    app.kubernetes.io/name: mcp
    app.kubernetes.io/component: cypher
    app.kubernetes.io/part-of: neo4j-mcp
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: mcp
    app.kubernetes.io/component: cypher
  ports:
  - name: http
    port: 8001
    targetPort: 8001
  type: ClusterIP