apiVersion: v1
kind: Service
metadata:
  name: mcp-memory
  labels:
    app.kubernetes.io/name: mcp
    app.kubernetes.io/component: memory
    app.kubernetes.io/part-of: neo4j-mcp
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: mcp
    app.kubernetes.io/component: memory
  ports:
  - name: http
    port: 8002
    targetPort: 8002
  type: ClusterIP