apiVersion: v1
kind: Service
metadata:
  name: mcp-modeling
  labels:
    app.kubernetes.io/name: mcp
    app.kubernetes.io/component: modeling
    app.kubernetes.io/part-of: neo4j-mcp
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: mcp
    app.kubernetes.io/component: modeling
  ports:
  - name: http
    port: 8004
    targetPort: 8004
  type: ClusterIP