apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-modeling
  labels:
    app.kubernetes.io/name: mcp
    app.kubernetes.io/component: modeling
    app.kubernetes.io/part-of: neo4j-mcp
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mcp
      app.kubernetes.io/component: modeling
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mcp
        app.kubernetes.io/component: modeling
        app.kubernetes.io/part-of: neo4j-mcp
        app.kubernetes.io/version: v1.0.0
    spec:
      serviceAccountName: mcp-neo4j-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: modeling
        image: ghcr.io/memenow/mcp-neo4j-data-modeling:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8004
          name: http
          protocol: TCP
        env:
        - name: MCP_TRANSPORT
          valueFrom:
            configMapKeyRef:
              name: mcp-app-config
              key: NEO4J_TRANSPORT
        - name: NEO4J_MCP_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: mcp-app-config
              key: NEO4J_MCP_SERVER_HOST
        - name: NEO4J_MCP_SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: mcp-app-config
              key: MODELING_PORT
        - name: NEO4J_MCP_SERVER_PATH
          value: "/api/mcp/"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: mcp-app-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
            ephemeral-storage: "500Mi"
          limits:
            memory: "256Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        livenessProbe:
          tcpSocket:
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8004
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: tmp
          mountPath: /tmp
          readOnly: false
        - name: cache
          mountPath: /.cache
          readOnly: false
        - name: venv
          mountPath: /app/.venv
          readOnly: false
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      - name: venv
        emptyDir: {}